# Generated by Django 4.1.7 on 2023-03-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_comment_created_at_comment_modified_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
