# Generated by Django 4.1.7 on 2023-03-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_authorprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
