# Generated by Django 4.1.7 on 2023-04-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="value",
            field=models.TextField(max_length=100, unique=True),
        ),
    ]
